### ISSUE TITLE
Error in 8.1.5

### ISSUE THREAD

**Issue by Admoney70** [brittyazel/RaidFrameIndicators#12]
94017x ...eRaidFrameIndicators\RaidFrameIndicators-1.0.5a.lua:415: bad argument #1 to 'find' (string expected, got nil)
[C]: in function `find'
...eRaidFrameIndicators\RaidFrameIndicators-1.0.5a.lua:415: in function `UpdateUnitAuras'
...eRaidFrameIndicators\RaidFrameIndicators-1.0.5a.lua:228: in function `UpdateIndicatorFrame'
...eRaidFrameIndicators\RaidFrameIndicators-1.0.5a.lua:196: in function `func'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:325: in function `applyFunc'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:121: in function `CompactRaidFrameContainer_ApplyToFrames'
...eRaidFrameIndicators\RaidFrameIndicators-1.0.5a.lua:196: in function <...eRaidFrameIndicators\RaidFrameIndicators.lua:195>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[2]"]:9: in function <[string "safecall Dispatcher[2]"]:5>
(tail call): ?
...eQuartz\libs\AceBucket-3.0\AceBucket-3.0-3.lua:116: in function `func'
...ceDetails\Libs\AceTimer-3.0\AceTimer-3.0-17.lua:57: in function <...ceDetails\Libs\AceTimer-3.0\AceTimer-3.0.lua:50>

**Comment by brittyazel** [comment]
hrm, this doesn't seem like it would be new in 8.1.5...

Can you try the latest release in MASTER and  tell me if that works for you? The only reason this error should be occurring is if the database isn't loading by the time the game is running.

Can you test with this being the only addon enabled as well and tell me if the problem still exists?

**Comment by Admoney70** [comment]
I saw you updated today, I had a long day at work and haven't had a chance to test.
I will let you know, thanks!
