### ISSUE TITLE
Show Buffs Disable

### ISSUE THREAD

**Issue by CDub619** [brittyazel/RaidFrameIndicators#17]
Still shows the Blizz buffs upon re-logging or reloading sometimes, it 100% happens when I re-log, then I have to go into the options and click it on and off a few times to stop the Bliz Buffs from showing.

**Comment by brittyazel** [comment]
Hrm ok. Seems like some PCs hit the first "hide" command on login and others don't. Mine hits it 100%, but it's useful to know thats not the case for everyone. No worries I can get it sorted
