### ISSUE TITLE
RFI is attaching itself to nameplates

### ISSUE THREAD

**Issue by Hofflerand2** [brittyazel/RaidFrameIndicators#18]
![1](https://user-images.githubusercontent.com/30275556/65726502-3b324a80-e083-11e9-92e4-2ac525e18f3e.jpg)

This is with the most recent update of Raid Frame Indicators. I disabled the nameplate add-on I usually use (flyPlateBuffs).

Issue 1: As you can see in the screenshot from the duplicate Hammer of Justice icon with the RFI text, RFI is showing debuffs on nameplates.
Issue 2: I cannot click nameplates at all anymore. It's like dead space. Clicking nameplates won't switch targets, and when I click on a nameplate (either left or right click) and hold that mouse button down, I can't swing my screen around.

I reset my RFI profile and disabled all other addons but that didn't fix it. I don't mean to pester you to fix this if I'm the only one experiencing it, but if others are as well then it's pretty game-breaking. Thanks again! Good luck.

**Comment by brittyazel** [comment]
Hrmmm.... Very odd. Blizzard must have somehow unified the raid frames code with the nameplate code behind the scenes. That's the only way this could be happening. Ugh Blizzard! You're killing me. 

Give me a couple hours to get a new build out and I'll see if I can get the fix in there
