### ISSUE TITLE
Suggestion: Fade out of range players

### ISSUE THREAD

**Issue by myzb** [brittyazel/RaidFrameIndicators#23]
I've seen you enhancing the addon a bit as of late and have a suggestion that maybe will also appeal to you.

The feature I'm talking is basically the option to set the frame alpha for players that are in- and out-of-range. There is an addon which already does this and works great, so baking this into your addon is not a prio but may complement it nicely without overbloating it with features.

Anyway the addon I'm talking is this one: https://www.curseforge.com/wow/addons/raidfademore

Having a similiar option just to adjust the alpha of people in and out of range would be nice.

**Comment by brittyazel** [comment]
So the game already does this by default, you'd just like the option to set "how much" alpha is applied?

**Comment by myzb** [comment]
Exactly. A slider or something to set the alpha of out of range targets. Perhaps 2 sliders one for in-rage alpha and one for out of range. I find the blizzard default alpha not as noticeable specially when raid healing as there is a lot going on.

As I said this is just a small idea which could complement you addon nicely. I'm currently using the before mentioned addon for this, which despite not being updated since 8.0.1 still works.

**Comment by brittyazel** [comment]
Yeah I had a look at that addon and the CPU ussage is crazy high. I'll have to figure out a way to do it that's different than hooking OnUpdate(). I wouldn't be surprised if that addon was dropping your fps by 4-5% 😕

**Comment by stefan0uh** [comment]
https://github.com/brittyazel/RaidFrameIndicators/blob/1172c9ede0d874d7b9d93cfefa73ff6bbce99dba/EnhancedRaidFrames.lua#L40-L50

`hooksecurefunc("CompactUnitFrame_UpdateInRange", CompactUnitFrame_UpdateInRange)`

The alpha range is between 0 and 1
I did something like that, for custom ranges (cause not all classes to need a 40 yards range)

```
function CompactUnitFrame_UpdateInRange(self)
    if string.match(self.unit, "party") or string.match(self.unit, "raid") then
        local inRange = IsSpellInRange(addon.db.profile.range.spell, self.displayedUnit)
        if inRange == 1 then
            self:SetAlpha(addon.db.profile.range.alpha.maximum)
            self.background:SetAlpha(addon.db.profile.range.background.maximum)
        else
            self:SetAlpha(addon.db.profile.range.alpha.minimum)
            self.background:SetAlpha(addon.db.profile.range.background.minimum)
        end
    end
end
```

**Comment by brittyazel** [comment]
This is fixed
