### ISSUE TITLE
Cant monitor Fearward

### ISSUE THREAD

**Issue by cyrax9** [brittyazel/RaidFrameIndicators#24]
I cannot see active fearwards in my raidgroup - WoW classic

any idea?

**Comment by cyrax9** [comment]
Update: i can see Fearward now BUT i also monitor renew.
everytime renew is active on the target the icon is in teh ssame position as ferward - so i cant see the fearward.

**Comment by brittyazel** [comment]
yes, the way it is coded right now, each spot will only show a single icon, and whichever the most recent icon to update will show over the top of any others in the same position. I recommend you put different abilities into different positions, which will allow you to see 9 different auras at once.
