### ISSUE TITLE
Stacks not working in the new versions.

### ISSUE THREAD

**Issue by fisken1991** [brittyazel/RaidFrameIndicators#25]
Focused Growth stacks not showing anymore. Using like 3-4 versions prior to the release so it works. 

![image](https://user-images.githubusercontent.com/18520277/69413175-9ba2d880-0d10-11ea-8362-6e0858920597.png)

![image](https://user-images.githubusercontent.com/18520277/69413263-c68d2c80-0d10-11ea-8566-c8fce907da8f.png)

**Comment by fisken1991** [comment]
It works in version 2.0.6

**Comment by brittyazel** [comment]
hrm...all of my stacks are working. I'll invistigate further. Is this still an issue or can we close?

**Comment by brittyazel** [comment]
Didn't respond so closing
