### ISSUE TITLE
Icon on "Show only if missing"

### ISSUE THREAD

**Issue by stefan0uh** [brittyazel/RaidFrameIndicators#27]
Is it possible to add the first Buff/Debuff icon to show when "only if missing" is checked? Instead of the dot.

![image](https://user-images.githubusercontent.com/5527697/72221409-c6fcb380-355a-11ea-837d-d8743674324c.png)

**Comment by brittyazel** [comment]
The dot isn't part of the addon. It's part of the built in frames. You can disable it from the main Enhanced Raid Frames options page

**Comment by stefan0uh** [comment]
Mhh I can change it just from `dot` to `?` cause it a font, not the behavior I expected.
Not as I expected when the `Show only if missing` is checked, the function should be negated so a `Spell Icon` is visible not a Dot (maybe an extra checkbox with "show an icon or dot")

![image](https://user-images.githubusercontent.com/5527697/72224509-a55ff400-357b-11ea-89d2-09b87e730bdb.png)

**Comment by brittyazel** [comment]
I'm getting confused. Can you screenshot the actual raid frame to show me what you mean? We might be talking about two different things

**Comment by stefan0uh** [comment]
I mean instead of this red `dot` i excepted a `spell icon` when I activate `Show only if missing`.

![image](https://user-images.githubusercontent.com/5527697/72226108-8c603e80-358d-11ea-8d15-39ce610a844d.png)

**Comment by brittyazel** [comment]
Oh by dot your mean square lol. Usually dot implies circle hence why I was so confused.

**Comment by stefan0uh** [comment]
oh... shit true, meant square.

**Comment by brittyazel** [comment]
This is fixed. Please test
