### ISSUE TITLE
earth shield

### ISSUE THREAD

**Issue by KritikaLdg** [brittyazel/RaidFrameIndicators#3]
Hi whenever i add Earth shield as a buff to track to place on the left side, it always seems to appear in the bottom right hand corner even though i havent asked it to... 

any ideas?

**Comment by brittyazel** [comment]
can you screenshot your config page so I can see what's going on? Thanks

**Comment by KritikaLdg** [comment]
which is the config page dude?

Thanks

Luke

**Comment by KritikaLdg** [comment]
oh wow i rebooted the game and now its working fine.... sorry for the
inconvenience.

**Comment by brittyazel** [comment]
Ok. And for the record, the config page is the one in the interface menu labeled "raid frame Indicators"
