### ISSUE TITLE
Defaulting to 'fallback' icon

### ISSUE THREAD

**Issue by numbdig** [brittyazel/RaidFrameIndicators#35]
I am using this for Classic and it works great!

 

One problem I am encountering - for my name in the raid frames, if I do not have a raid icon assigned to me, a green box will appear. The fix for this is to give me a raid icon and then clear it - but it will periodically come back. Is there an easy fix for this?

 
![image](https://user-images.githubusercontent.com/65259980/81754073-3e980c00-9483-11ea-9da3-5bfc487d1074.png)

**Comment by brittyazel** [comment]
Alrighty, I have no idea why this issue occurred in the first place, but this should effectively fix it!

**Comment by numbdig** [comment]
Thanks man! Just testing it outside of raid - it seems to be working :)

**Comment by brittyazel** [comment]
Excellent! 👍

**Comment by brittyazel** [comment]
Can you do me a favor? I added tentative support for libclassicdurations but I don't have any way to test it. Do you mind testing it out and seeing if spells on classic have the correct countdowns and whatnot with the changes I made? You'll have to snag the version from Github and install it manually

**Comment by numbdig** [comment]
Sure! I'll be back online later this evening and will let you know if it works at all.

**Comment by numbdig** [comment]
![image](https://user-images.githubusercontent.com/65259980/81876086-dcf1a380-954f-11ea-97fe-24f3cfab51f8.png)
Seems to be working :)

**Comment by brittyazel** [comment]
Great! Did the countdown not work prior?

**Comment by numbdig** [comment]
I just re-installed the previous version - seems to be working just fine.

**Comment by brittyazel** [comment]
I pushed a new release with these code changes immediately after you gave me to thumbs up, so it's likely if you reinstalled from Twitch/Curseforge you got the exact same version as here
