### ISSUE TITLE
Bug with tooltip

### ISSUE THREAD

**Issue by Cocodec** [brittyazel/RaidFrameIndicators#8]
Hello,

It happens very regularly that the addon bug the tooltip. I do not really know exactly what causes this bug but the tooltip is "locked" to that of my character ... So I can not look at the tooltip of my spells or pieces of stuff anymore.

Thanks for your work.

**Comment by brittyazel** [comment]
Yeah I've noticed this as well. I'll check into it and see what I can sort out

**Comment by Cocodec** [comment]
Thanks !

**Comment by Fethbita** [comment]
After some testing I found out that this only happens after a /reload. I feel like `function RaidFrameIndicators:OnEnable()` does not work after a reload.

**Comment by brittyazel** [comment]
Hrm, that's odd. It should be.... if it's not that's a HUGE issue. Thanks for looking into this

**Comment by Fethbita** [comment]
It does indeed run after a reload but I don't know why I can't see the tooltips after a reload. The only addons I have active are Blizzard Raid Frames - Solo Frame and Raid Frame Indicators + Icons. It might be that Solo Frames is doing something wrong. But I can consistently reproduce tooltips not showing after reloading while solo.

**Comment by Cocodayc** [comment]
Still no solution ? I would love to use this addon but I can not because of this bug ...

Thanks.

**Comment by brittyazel** [comment]
I haven't yet tried to solve it. I'll do that soon! Sorry I only have so much time to split between all my add-ons lol. Give me a bit and I'll see what I can do

**Comment by Cocodayc** [comment]
Thank you very much for the work you do for the community.

**Comment by brittyazel** [comment]
All fixed!!

@Cocodayc care to test the new version and report back? I had to pretty substantially rework s the tooltip system, but it seems to work as expected for me :-)

Thanks for the push to finally get this fixed. I too was annoyed by it

**Comment by Respekt93** [comment]
Yo,

in the newest Version..The tooltips appearing and disappearing 5 tims in the second xD In 1.02 it doesnt.

**Comment by brittyazel** [comment]
It should be doing that... Hrm. In 1.0.2 the tooltips weren't even working for me at all. So you're saying when you just have the cursor hovering over a single spell it appears and disappears repeatedly?

**Comment by brittyazel** [comment]
@Respekt93 fixed!

**Comment by Respekt93** [comment]
Ty Mate :)

**Comment by Cocodayc** [comment]
Works perfectly, thanks !
